### ISSUE TITLE
Backup upload images

### ISSUE THREAD

**Issue by kosssi** [linuxserver/docker-hedgedoc#18] opened 2021-09-15 21:17 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

When I restart container I would like display uploaded picture.

## Current Behavior

When I restart container all picture uploaded are deleted.

## Steps to Reproduce

1. Create a note on hedgedoc
2. Upload picture on this note
3. Restart container
4. Picture not display

On documentation you should attach volume on /path/to/config:/opt/hedgedoc/public/uploads

**Comment by aptalca** [comment] 2021-09-15 21:42
need to fill out the issue template

**Comment by thomaswucher** [comment] 2021-11-23 19:09
I just ran into this issue today, and I lost data because it is nowhere mentioned that a separate volume for uploads needs to be created. Every user of this docker image will eventually loose data, so in my opinion this needs a fix as soon as possible.

I'm not sure why this is marked as having insufficient info, because the issue description provides steps to reproduce and even the correct solution. Given the seriousness of this issue (production data loss) I don't get why this was never fixed!?

**Closed** 2021-12-08 13:17 UTC
Labels: invalid
